path: E:\SLIIT\__4th_Year\Research Project - IT4010\dev\ENT-disease-detection-dl-models\sinusitis_detection_and_severity_classification\annotate_maxillary\yolov8\dataset\detect
train: images/train 
val: images/val 
test: images/test 

nc: 2
names:
  0: left
  1: right