path: E:\SLIIT\__4th_Year\Research Project - IT4010\dev\ENT-disease-detection-dl-models\sinusitis_detection_and_severity_classification\annotate_maxillary\yolo\dataset\detect
train: images/train 
val: images/validation
test: images/test 

nc: 3
names:
  0: Healthy
  1: Moderate
  2: Severe